apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |-
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    clientConnection:
      kubeconfig: /etc/kubernetes/scheduler.conf
    profiles:
    - schedulerName: custom-scheduler
      plugins:
        # filter:
        #   enabled:
        #   - name: DriftPlugin
        # score:
        #   disabled:
        #   - name: "*"
        #   enabled:
        #   - name: DriftPlugin
        #     weight: 1
        filter:
          enabled:
            - name: NodeResourcesFit
            - name: PodTopologySpread
            - name: NodeUnschedulable
        score:
          enabled:
            - name: NodeResourcesFit
            - name: PodTopologySpread
